spring.application.name=ProgInz_TDLS_SSS


spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/tdls_sss_project
spring.datasource.username=userspring3
spring.datasource.password=parole
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
